### ISSUE TITLE
[ Bug ] Logo selection not visible

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/logo-maker#56]
Button text color overrides the logo selection illustrations inside the buttons [here](https://themeisle.com/logo-maker/logo-wizzard/#/creator).

This can easily be fixed by overriding the variable on the `.logo-list` selector:

```
--primaryBtnColor: #000;
```

![image](https://user-images.githubusercontent.com/15010186/148361630-cb7b4632-5c7b-47b4-95b1-0a4c8a821fb9.png)

**Comment by Soare-Robert-Daniel** [comment]
This was caused by WP defaults on the `button`. A better solution is to enforce the color. Thanks for reporting 🍺 

Fix Commit: 3fbb526076494a7c511c33eed8f4d3822bcbf08a
